version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  pre_build:
    commands:
      # Install dependencies needed build process
      - npm install

  build:
    commands:
      # build app
      - npm run build

  post_build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      # WEBSITE_S3_BUCKET = ----ui-app
      # WEBSITE_BUCKET = troperial.com
      - echo WEBSITE_S3_BUCKET = $WEBSITE_S3_BUCKET
      - echo WEBSITE_BUCKET = $SWEBSITE_BUCKET
      - aws s3 cp --recursive ./build/ s3://$WEBSITE_S3_BUCKET/public/
      - aws s3 sync s3://$WEBSITE_S3_BUCKET/public/ s3://$WEBSITE_BUCKET/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  type: zip

