/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:e6afed6b-c23d-4f01-a2a4-6a1fd502e77a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_UVrmOc80q",
    "aws_user_pools_web_client_id": "1l7b0cc253j73hit6l8j2o1vtn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://192.168.56.1:20002/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


export default awsmobile;
