/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vpmttarj7vcnta6g3pufvf67mu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3dbdq7ezozfolgbyktggrln33i",
    "Auth": {
        "mandatorySignIn": true,
        "region": "us-east-1",
        "userPoolId": "us-east-1_0fIbiKHAY",
        "userPoolWebClientId": "ts2d0dsgphtpjjv2qpkc2t1e9"
    }
};


export default awsmobile;
